### ISSUE TITLE
Should target .NET 4.7.2, not .NET 4.8

### ISSUE THREAD

**Issue by arknu** [YourITGroup/OpenOrClosed#1]
Thank you for making this package 😃 

This package targets .NET 4.8, while the minimum requirement for Umbraco 8 is .NET 4.7.2. This makes it impossible to install this package on a project targeting .NET 4.7.2.

Given the very minor differences between 4.7.2 and 4.8, I believe that there should be no problem in retargeting to .NET 4.7.2 and thus making it compatible with all Umbraco 8 solutions.

**Comment by robertjf** [comment]
hm.  Yep, will get on it :)

**Comment by robertjf** [comment]
Done - thanks for the pick up 👍
