### ISSUE TITLE
Ability to set a custom label for the states instead of open / closed

### ISSUE THREAD

**Issue by nzdev** [YourITGroup/OpenOrClosed#2]
It would be awesome to be able to change the label from open / closed on a per property basis. Example. On Air / Off Air. Online / Offline etc.

**Comment by robertjf** [comment]
great suggestion - I'll take a look into it when I can (probably next week but no promises) unless you want to create a PR?

**Comment by robertjf** [comment]
@nzdev just released a new version for you with this implemented - let me know how it goes for you 👍

**Comment by nzdev** [comment]
Thanks so much! I'll give this a go and let you know.
