### ISSUE TITLE
Make close time mandatory

### ISSUE THREAD

**Issue by philipdanielhayton** [YourITGroup/OpenOrClosed#29]
Hi guys,

First of all thanks for this package! 

I was wondering if it would be possible to make the close time an optional field per configuration. In our use case we don't actually care about the close time, but it triggers Umbraco validation error if we leave it blank.

Any help is greatly appreciated!

TIA

**Comment by robertjf** [comment]
Thanks for the suggestion @philipdanielhayton - I've just implemented it in release 1.1.0 - give it a try and let me know what you think, this is considered experimental at the moment :)
