### ISSUE TITLE
dotnet add package OpenOrClosed does not work on 9.5.0 version of Umbraco

### ISSUE THREAD

**Issue by acbach** [YourITGroup/OpenOrClosed#30]
Tried to install this on newest version on Umbraco. 
But no luck.
Installation does does not show up in "installed packages" tab with other installation
![image](https://user-images.githubusercontent.com/43601099/175537951-8680e676-4af9-4589-bfec-b9d2c210c61c.png)

**Comment by robertjf** [comment]
Hi @acbach a couple of questions for you:
1. How did you install the package?
2. What version did you install?
3. What version of Umbraco are you installing on (specifically - 9.5.0, 9.5.2, something else...)?

**Comment by acbach** [comment]
Hi @robertjf 

1. Installed through Rider using dotnet add command

2. Newest version 1.0.3

3. We are using 9.5.0

**Comment by robertjf** [comment]
Hi @acbach I tested this with a new Umbraco 9.5.2 build, and installed the package using Nuget Package Manager - here's what the Project file looks like:
![image](https://user-images.githubusercontent.com/818101/177043459-c828a965-52d7-427e-8b7b-06e2e731ff7b.png)

I also tested creating a document type and document with one of the Properties (Special Business Hours), and everything works as expected.

However, it does not show up under Packages (it does however for Umbraco 10) - so I suspect this is an Umbraco 9 issue, not a package issue.

Double check that your project(s) include the PackageReference entries for the appropriate version - if they do, you should be good to go without having to worry about whether you can see it under Packages or not.
