### ISSUE TITLE
Odd behaviour with language files

### ISSUE THREAD

**Issue by SonniTost** [YourITGroup/OpenOrClosed#32]
We are using the OpenOrClosed package on a couple of Umbraco 9 solutions (9.2 and 9.52) and experience an odd behaviour regarding the language shown.

We have two languages Danish and English (and two language files).
We have made some centrally stored contact groups that make use of the OpenOrClosed features that can be used across the site multiple times. That means that we use a Multinode Tree Picker to select the contact groups.

The site has been setup using cultures - but it does not seem to affect the output.

But the image below shows the two contact groups on the same page - and both of the contact groups should show the same language version. But it doesn't.

I have updated the different caches and rebuild the external index - but it does not help.

![image](https://user-images.githubusercontent.com/66302306/189330628-c2ea05c7-079c-40a9-b773-588252201cad.png)

**Comment by robertjf** [comment]
Hey @SonniTost odd indeed... it's likely an issue with umbraco and/or your implementation, as there's nothing in the code that would cause this behaviour - happy to take a look for you, but would need a reproducible sample of the code/database...

**Comment by abjerner** [comment]
The issues occurs because the value of `dayoftheweek` property is the localized day of the name, so if the user has selected English for the backoffice language, English day names are saved (and returned by the value converter). If the backoffice language is Danish, the day names will instead be saved in Danish.

So ultimately it comes down to the backoffice language of the user at the time the opening hours are saved:

https://github.com/YourITGroup/OpenOrClosed/blob/master/OpenOrClosed/App_Plugins/OpenOrClosed/js/StandardHours.controller.js#L102

I'd say ideally the JSON data should always only have the English days names, and then be represented by something like the `DayOfWeek` enum or the localized day name in the model returned by the value converter. But this may be hard to fix retroactively.

**Comment by SonniTost** [comment]
Hi @robertjf 
Thanks for the quick response!
Luckily @abjerner is a colleague of mine and he has made a property value converter that has fixed it on our solution.

**Comment by robertjf** [comment]
thanks guys, I'll look into fixing it in an upcoming release - if you'd like to take a stab and submit a PR I'll happily accept that too :)

**Comment by abjerner** [comment]
I think the biggest issue with creating a fix is that it's hard to account for all the localized values that may already be saved, as I can't think of a good way to determine the culture/language in which the days are saved.

In our case, we only have to account for English and Danish names, so I ended up writing the following value converter:

```csharp
using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using OpenOrClosed.Core.ViewModels;
using Skybrud.Essentials.Json;
using Skybrud.Essentials.Json.Extensions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PropertyEditors;

namespace Client.Hacks.OpenClosed {
    
    public class OdStandardHoursConverter : PropertyValueConverterBase {

        public override bool IsConverter(IPublishedPropertyType propertyType) {
            return OpenOrClosed.Core.Constants.PropertyEditors.Aliases.StandardHours == propertyType.EditorAlias;
        }

        public override Type GetPropertyValueType(IPublishedPropertyType propertyType) {
            return typeof(IEnumerable<OdDaysViewModel>);
        }

        public override PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType) {
            return PropertyCacheLevel.Element;
        }

        public override object ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, object source, bool preview) {
            return source is string json ? JsonUtils.ParseJsonArray(json) : null;
        }

        public override object ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, object inter, bool preview) {

            if (inter is not JArray array) return Array.Empty<OdDaysViewModel>();

            List<OdDaysViewModel> temp = new();

            foreach (JToken token in array) {

                if (token is not JObject obj) continue;

                string dayOfTheWeek = obj.GetString("dayoftheweek");

                DayOfWeek day;
                switch (dayOfTheWeek?.ToLowerInvariant()) {
                    case "monday":
                    case "mandag":
                        day = DayOfWeek.Monday;
                        break;
                    case "tuesday":
                    case "tirsdag":
                        day = DayOfWeek.Tuesday;
                        break;
                    case "wednesday":
                    case "onsdag":
                        day = DayOfWeek.Wednesday;
                        break;
                    case "thursday":
                    case "torsdag":
                        day = DayOfWeek.Thursday;
                        break;
                    case "friday":
                    case "fredag":
                        day = DayOfWeek.Friday;
                        break;
                    case "saturday":
                    case "lørdag":
                        day = DayOfWeek.Saturday;
                        break;
                    case "sunday":
                    case "søndag":
                        day = DayOfWeek.Sunday;
                        break;
                    default:
                        throw new Exception($"Unsupported value {dayOfTheWeek}");
                }

                bool isOpen = obj.GetBoolean("isOpen");
                var hoursOfBusiness = obj.GetObjectArray<HoursViewModel>("hoursOfBusiness");

                temp.Add(new OdDaysViewModel(day, isOpen, hoursOfBusiness));

            }

            return temp;

        }

    }

}
```

**Comment by robertjf** [comment]
@SonniTost and @abjerner I've got a pre-release for 2.0.0 targeting Umbraco 10+ only out shortly; this version includes the Systme.DayOfWeek in the data so you don't need to extrapolate it yourselves - this should allow the flexibility of displaying the Day in the current locale.

Open to suggestions, if you think the new code can be improved I'm all up for it :)
