### ISSUE TITLE
Request: add textarea to umb-date-time-picker

### ISSUE THREAD

**Issue by lassespilling** [YourITGroup/OpenOrClosed#51]
Hi!
Love your package, only one thing i am missing.
The ability to write a short text comment via a textarea to each date row.

E.g. a 
09:00-12:00 Svimming for seniors
12:00-15:00 Babysvimming

**Comment by lassespilling** [comment]
I was able to fork and create the functionality myself.
[Link to fork](https://github.com/lassespilling/OpenOrClosed-with-comments)

![Thumbnail of fork](https://gcdnb.pbrd.co/images/FxnXhOcau8p8.jpg?o=1)

**Comment by robertjf** [comment]
Awesome @lassespilling  - can you create a Pull Request from your fork back to this repository and we'll get it released

#H5YR

**Comment by robertjf** [comment]
Hi @lassespilling thanks again for your contribution, I ended up re-creating most of what you had with a few minor enhancements - release 2.0.5 should be out soon.
