### ISSUE TITLE
Issues saving the document when new holiday (closed) day is added, and hours are optional

### ISSUE THREAD

**Issue by james-whittington1** [YourITGroup/OpenOrClosed#59]
Using Umbraco 12 I have set up a holiday hours with optional times, when I save the document it shows a validation error, and I need to click the "switch" to set the day as open, which then shows the hours. 

I think there may be a logic error as the ng-required for the hour fields is only checking if the hours are completely excluded, however if they are not excluded, but are optional, a validation error is raised.

I believe that the ng-required for the hour fields should instead be looking something like this:
!model.config.hoursOptional || !model.config.closedHoursOptional 

I am a little unsure of how the logic for closedHoursOptional should work so I thought I would start an issue rather than just firing off a PR

Thanks for the great library :)

**Comment by robertjf** [comment]
Thanks @james-whittington1 - you were close - the ng-required was missing the hoursOptional flag.

This is fixed in 3.0.1
