### ISSUE TITLE
Unable to save properties using only the core package

### ISSUE THREAD

**Issue by nzdev** [YourITGroup/OpenOrClosed#6]
Unable to save properties using only the core package.
Needs to have the contents of OpenOrClosed/PropertyEditors/ moved to the core package.

**Comment by robertjf** [comment]
sorry for the late reply, that folder isn't actually compiled into the dlls at all yet, the Property Editors are defined in the package.manifest currently - something I'll change in the near future...

**Comment by robertjf** [comment]
@nzdev this should now be resolved as I've added the property editor definition from the manifest to the core package.  Please let me know if you still have problems...
