### ISSUE TITLE
Special business hours - date not shown if line is "closed"

### ISSUE THREAD

**Issue by Stentoft** [YourITGroup/OpenOrClosed#7]
Umbraco version 8.8.3

When creating a not open ("closed") day/date under Special business hours, the date is not shown, next time you come back to the item.
But - if you click the date picker, the correct/previously selected date is already selected.
As shown in the attached screenshots.

<img width="1702" alt="Screenshot 2021-02-16 at 15 26 34" src="https://user-images.githubusercontent.com/10901104/108076581-e1f9fb00-706b-11eb-97c8-c061230cdd8d.png">
<img width="1695" alt="Screenshot 2021-02-16 at 15 27 18" src="https://user-images.githubusercontent.com/10901104/108076593-e6261880-706b-11eb-9a84-40b21a3334c6.png">

**Comment by robertjf** [comment]
@Stentoft thanks for picking this up - I've just released a new version which should fix this if you could check it out.  (I have tested, but having you verify would be great)

**Comment by Stentoft** [comment]
@robertjf I can now confirm it working in my end as well. (v. 0.1.5)
- Thank you so much for the quick response :-) 🙏
